# Generated by Django 3.2.11 on 2022-01-15 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cowwise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuuid',
            name='val',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
